task: medec

models:
  - azure_gpt5_medium
  - azure_o3_medium
  - claude-sonnet-4-thinking
  - deepseek-r1-0528
  - unsloth-gpt-oss-20b-low
  - unsloth-gpt-oss-20b-medium
  - unsloth-gpt-oss-20b-high
  - unsloth-gpt-oss-120b-low
  - unsloth-gpt-oss-120b-medium
  - unsloth-gpt-oss-120b-high
  - preferred-medrect-32b
  - qwen3-32b-local

  - gpt-4_1
  - deepseek-v3-0324
  - qwen3-32b-no-think-local

datasets:
  - medrect_ja

templates:
  - 0_shot_ja

output_dir: results
